### ISSUE TITLE
"Set" value should allow string

### ISSUE THREAD

**Issue by josheinhorn** [lukevenediger/statsd-csharp-client#14]
So it is not at all clear from Etsy's docs, but I have confirmed that the Etsy StatsD server works with `string` Set values (e.g. `userIds.unique:josheinhorn|s`).  I've also seen other StatsD client implementations allow sending `string` values for the Set metric type.

This would be highly useful since it's a very common occurrence to need to count unique occurrences of text values in addition to numeric values. For instance, you might want to count unique users that have User IDs with combinations of letters and numbers (think GUID), or count unique IP addresses (which _appear_ to be numeric, but are obviously not).

Would of course be happy to take on the PR for this unless someone objects.

**Comment by niemyjski** [comment]
Can you submit a pr for this?

**Comment by niemyjski** [comment]
Can you submit a pr for this?

**Comment by josheinhorn** [comment]
Hey @niemyjski -- sorry I never followed up with this back in 2016. I've actually been out of the C# game for well over 2 years now, so I'm probably not the best guy to do this anymore 😳

Would you like me to close this issue?
