### ISSUE TITLE
project maintained?

### ISSUE THREAD

**Issue by TerribleDev** [lukevenediger/statsd-csharp-client#17]
Hi,

is this project maintained? I am very interested in porting this project to core. Also I have found some improvements in the async layer. 

For now I'm going to fork this repo, and continue the work.

**Comment by niemyjski** [comment]
I'm not currently using this library in production but I'm helping maintain it, If you run across an issue let us know. Also we are more than happy to accept pr's.  On a side note, I created and maintain Foundatio (https://github.com/exceptionless/Foundatio#metrics) and we do abstracted metrics with a statds implementation (librato).

**Comment by TerribleDev** [comment]
Is there any plan to publish the async work that was committed a long time back?

**Comment by niemyjski** [comment]
@TerribleDev We'd accept it after the pr is updated. There are currently issues with the pr.

**Comment by niemyjski** [comment]
Actually, I stand corrected, it was merged in :) https://github.com/lukevenediger/statsd-csharp-client/pull/9/files one of the pr's that has async fixes has issues.

**Comment by niemyjski** [comment]
Is this released on nugget? @lukevenediger what needs to happen to release new versions?

**Comment by lantrix** [comment]
@niemyjski doesn't seem to be on nuget yet. Given it is > 1 year, probably just roll your own local 1.4.0 version.

**Comment by niemyjski** [comment]
I'll reach out to @lukevenediger and see if he can add me to the nuget package owners so I can setup a new ci build and get packages flowing!

**Comment by lantrix** [comment]
Good idea. We have 1.4.0 on our own internal nuget server though for the async improvements 👍 Would be nice to remove that.

**Comment by TerribleDev** [comment]
Yeah I ended up [rolling my own](https://github.com/TryStatsN/StatsN). Not that this project isn't awesome (honestly it saved me many times) there were just things I wanted, and I am not a patient person I guess.

Thanks though!

**Comment by niemyjski** [comment]
I can't do anything until I'm listed as an owner on nuget (I can't push nuget updates until then) @lukevenediger

**Comment by niemyjski** [comment]
The package has been pushed (https://www.nuget.org/packages/StatsdCsharpClient/1.4.6) and a ci server set up (see readme)
