### ISSUE TITLE
Updating from 1.3.0 to 1.4.6 breaks my project

### ISSUE THREAD

**Issue by marginality4life** [lukevenediger/statsd-csharp-client#21]
Updating this nuget package broke my project - it caused it no longer output UDP messages. 

Project is here: 
https://github.com/paybyphone/statsd-helper-webapi

**Comment by niemyjski** [comment]
Were you able to narrow it down to what is causing the behavior? Is it a dead lock?

**Comment by niemyjski** [comment]
@marginality4life were you able to figure out this issue?
