### ISSUE TITLE
Bad performance of UDP client

### ISSUE THREAD

**Issue by majkinetor** [lukevenediger/statsd-csharp-client#5]
You should change UDP client so it cashes IP address instead obtaining it each time. The lag is enormous in web apps. Furthermore, if one already gives IP address there is no need to check for IP address. Next, If something is wrong with server name, UDP channel should be substituted with null channel. 

The statsd client should first perform well in order not to block application, then have good interface.

**Comment by niemyjski** [comment]
+1 we are also seeing socket exceptions

**Comment by ejsmith** [comment]
Yep, I am using this library in a couple apps and it will occasionally blow up.

**Comment by niemyjski** [comment]
@lukevenediger If you want to give me write permission, I'd be more than happy to review these pull requests and make some changes. I don't mind spending time on this lib as long as I know others can benefit as well.

**Comment by niemyjski** [comment]
@majkinetor I don't think we need to do the null channel fallback. I was hitting a lot of perf issues and connectivitely issues and it all came down to using the udp client. The solution is to use a socket and have it recreate the socket anytime there is an error. Also you can squeeze a bit more perf in other areas (I'll try and make this changes when ever I get some free time). I ended up writing a udp implementation for my project before I had write access here.. I took it from ~20k requests/s to over 90k requests/s with failover: https://github.com/exceptionless/Foundatio/blob/master/src/Core/Metrics/StatsDMetricsClient.cs

I run an oss project ( https://github.com/exceptionless/Exceptionless ), and it helped me find a lot of exceptions with the udp implementations.

**Comment by niemyjski** [comment]
I'm going to close this, if you can submit a pr for any perf improvements that would be greatly appreciated
